### ISSUE TITLE
-62 RSSI all sensors

### ISSUE THREAD

**Issue by huemcos** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#21] opened 2020-09-13 15:46 UTC
Thanks for a very nice custom component!

All sensors are showing -62 RSSI value. It started with version 0.6 and still the same in version 0.7, if this can be fixed it would be nice to tell whether a sensor is in a good bluetooth range.

**Comment by Thrilleratplay** [comment] 2020-09-13 17:57
@huemcos   This is known issue with [the bleson library](https://github.com/TheCellule/python-bleson/issues/44) but haven't had time to look into it.

UPDATE:  I think I found the cause and [entered a PR](https://github.com/TheCellule/python-bleson/issues/77) but would need to wait for it to be verified, merged in and a new package released.

**Comment by WayneKeenan** [comment] 2020-09-19 08:19
Hiya, a Bleson 0.1.6 package has been released which includes your PR.

**Comment by Thrilleratplay** [comment] 2020-09-19 14:31
@WayneKeenan   Thank you.

Fixed in v0.7.1

**Closed as completed by Thrilleratplay** 2020-09-19 14:31 UTC
