### ISSUE TITLE
Interrupted system call error

### ISSUE THREAD

**Issue by gmalbert** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#34] opened 2021-03-08 01:17 UTC
I'm using HA Container version 2021.2.3 with the 0.9.1 add in through HACS. I get the following error:

`Logger: homeassistant.components.sensor
Source: custom_components/govee_ble_hci/sensor.py:206
Integration: Sensor (documentation, issues)
First occurred: March 5, 2021, 9:50:35 AM (1 occurrences)
Last logged: March 5, 2021, 9:50:35 AM

Error while setting up govee_ble_hci platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/govee_ble_hci/sensor.py", line 206, in setup_platform
    adapter = get_provider().get_adapter(int(config[CONF_HCI_DEVICE][-1]))
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_provider.py", line 12, in get_adapter
    adapter.on()
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 97, in on
    self.send_cmd_value(HCIDEVUP, self.device_id)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 47, in send_cmd_value
    fcntl.ioctl(self._socket.fileno(), cmd, value)
InterruptedError: [Errno 4] Interrupted system call`

**Comment by Thrilleratplay** [comment] 2021-03-08 04:15
You are going to need to provide more context. 

* Were you using this component before without issue or is it newly installed?  
* What device is it running on?
*  Is it Home Assistant Operating System or a a docker container?
* Are there any other Bluetooth related components used in Home Assistant?

I suspect however it is configured, Home Assistant does not have access to the Bluetooth controller.

**Comment by gmalbert** [comment] 2021-03-08 11:35
@Thrilleratplay thanks for replying and happy to provide more context.

1) I had been using this component before without issue.
2) I'm running it on a RPI4.
3) HA is using a docker container.
4) I'm also using Room-Assistant which uses bluetooth.

Happy to troubleshoot in any way.

**Comment by Thrilleratplay** [comment] 2021-03-08 15:38
@gmalbert Taking a quick look at Room-Assistant, I suspect that the issue is a conflict between the two components as both seem to lock the Bluetooth adapter.  Recent changes in Room-Assistant may have made this more obvious.  To confirm, try disabling Room-Assistant, rebooting the RPI and see if this component starts working.  If it does, the only solutions I can think of are to either chose between the components or purchase an external Bluetooth adapter and configure each component to use their own adapter.

**Comment by Thrilleratplay** [comment] 2021-03-09 14:52
@gmalbert  I am going to close this ticket as it does not seem like a bug with the component.  If you need any more help with configuration, as stated in the README, should be asked on [this component's Home Assistant community post](https://community.home-assistant.io/t/govee-ble-thermometer-hygrometer-sensor/166696)

**Closed as completed by Thrilleratplay** 2021-03-09 14:52 UTC

**Comment by gmalbert** [comment] 2021-03-09 16:48
I apologize for not getting to this yesterday after I saw your comment. I removed room-assistant and restarted the pi. Upon restarting HA, I get the following error now:

`Logger: homeassistant.components.sensor
Source: custom_components/govee_ble_hci/sensor.py:206
Integration: Sensor (documentation, issues)
First occurred: 11:41:36 AM (1 occurrences)
Last logged: 11:41:36 AM

Error while setting up govee_ble_hci platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/govee_ble_hci/sensor.py", line 206, in setup_platform
    adapter = get_provider().get_adapter(int(config[CONF_HCI_DEVICE][-1]))
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_provider.py", line 12, in get_adapter
    adapter.on()
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 97, in on
    self.send_cmd_value(HCIDEVUP, self.device_id)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 47, in send_cmd_value
    fcntl.ioctl(self._socket.fileno(), cmd, value)
TimeoutError: [Errno 110] Operation timed out`

**Comment by Thrilleratplay** [comment] 2021-03-09 18:00
@gmalbert It is saying the bluetooth adapter cannot be connected to.  Either there is another component still using the bluetooth adapter or, assuming it was not changed in the config, another adapter has used `hci0`, to which try using `hci_device: hci1`.  If that does not resolve it, please post this in the community forum.  Others may have experienced a similar issue and found a solution.
